---
# This playbook manages bastion users
- hosts: bastions
  become: yes
  roles:
    - record_users
    - activate_new_users
    - remove_users

- hosts: localhost
  roles:
    - add_keypair
    - remove_keypair

- hosts: bastions
  become: yes
  roles:
    - set_authorized_key
    - send_private_key

