- name: Ensure the group exists
  group:
    name: "{{ group }}"
    state: present


- name: Allow group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%{{ group }} ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Add the user
  user:
    name: "{{ item }}"
    group: "{{ group }}"
    shell: /bin/bash
    create_home: yes
    state: present
    expires: -1
  with_items: "{{ users }}"
